# A workflow that only tests, but does not publish

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: xvfb-run mvn -T3 clean test





# TODO: Saint Coinach auto-update of data
# TODO: Cactbot timelines auto-update
